export enum EventType {
    ORDER_PLACED = 'ORDER_PLACED',
    ORDER_FILLED = 'ORDER_FILLED',
    ORDER_CANCELLED = 'ORDER_CANCELLED',
    TRADE_EXECUTED = 'TRADE_EXECUTED',
    ORDER_PENDING = 'ORDER_PENDING',
    ORDER_FAILED = 'ORDER_FAILED',
    OTPASKED='OTPASKED',
    OTPFAIL='OTP_FAILED',
}
